# Generated by Django 2.2 on 2019-04-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0013_add_required_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlagState',
            new_name='FlagCondition',
        ),
    ]
